name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch and pull updates
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SERVER_SSH_KEY}}
        script: |
          cd ~/projects/hrta-discord-bot/
          git pull
          pip install -r requirements.txt
          pm2 restart main.py --interpreter=/usr/bin/python3