name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to code
      uses: actions/checkout@v2
    - name: Fetch and pull updates
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SERVER_SSH_KEY}}
        passphrase: ${{secrets.SERVER_SSH_PASSPHRASE}}
        script: |
          cd ~/projects/hrta-discord-bot/
          git pull