name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ls -a via OPEN SSH Private Key
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
          echo "env_var:$FIRST_NAME"
          exit 1
        host: ${{ secrets.SSH_HOST }}
        user: ${{secrets.SSH_USERNAME}}
        key: ${{ secrets.SERVER_SSH_KEY}}
        #          pass: ${{ secrets.PASS }}

#    - name: Fetch and pull updates
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{secrets.SSH_HOST}}
#        username: ${{secrets.SSH_USERNAME}}
#        key: ${{secrets.SERVER_SSH_KEY}}
#        script: |
#          cd ~/projects/hrta-discord-bot/
#          git pull